import type { Project } from './types'

/** The single source of truth for project classification and ordering. */
export const projects: Project[] = [
  { id: 'huginn', title: 'Huginn', category: 'ai-systems', tier: 'flagship', status: 'unknown', featured: true, order: 1, bodyFileId: 'projects/ai-systems/huginn', summary: 'A durable, model-agnostic runtime for stateful AI agents.', stack: ['Typed tools', 'Persistent run state', 'Tracing', 'OpenAI-compatible endpoints'], github: 'https://github.com/nirupamc/huginn' },
  { id: 'syn', title: 'Syn', category: 'ai-systems', tier: 'flagship', status: 'unknown', featured: true, order: 2, bodyFileId: 'projects/ai-systems/syn', summary: 'A self-hosted, OpenAI-compatible inference gateway and control plane for local LLMs.', stack: ['FastAPI', 'Python', 'llama.cpp', 'SSE', 'Admission control'], github: 'https://github.com/nirupamc/syn' },
  { id: 'jung-archive', title: 'Jung Archive', category: 'ai-systems', tier: 'flagship', status: 'unknown', featured: true, order: 3, bodyFileId: 'projects/ai-systems/jung-archive', summary: 'A local-first document intelligence and evaluated retrieval system built around Carl Jung’s The Undiscovered Self.', stack: ['PyMuPDF', 'Tesseract', 'ChromaDB', 'BM25', 'Cross-encoder reranking'], github: 'https://github.com/nirupamc/jung-archive' },
  { id: 'munin', title: 'Munin', category: 'ai-systems', tier: 'flagship', status: 'unknown', featured: true, order: 4, bodyFileId: 'projects/ai-systems/munin', summary: 'Long-term memory infrastructure for AI agents.', stack: ['Semantic search', 'Memory admission', 'Deduplication', 'Temporal relevance', 'Namespace isolation'], github: 'https://github.com/nirupamc/muninn' },
  { id: 'aletheia', title: 'Aletheia', category: 'ai-systems', tier: 'featured', status: 'unknown', featured: true, order: 5, bodyFileId: 'projects/ai-systems/aletheia', summary: 'Local LLM benchmarking and profiling work.', github: 'https://github.com/nirupamc/Aletheia' },
  { id: 'aion', title: 'AION', category: 'creative-tech', tier: 'featured', status: 'active', featured: true, order: 13, bodyFileId: 'creative/technology/aion', summary: 'A browser-based music intelligence and DJ workflow system.', stack: ['Next.js', 'FastAPI', 'SQLite', 'Music metadata', 'Transition intelligence'], github: 'https://github.com/nirupamc/AION', live: 'https://aion-music.vercel.app/' },
  { id: 'ragparser', title: 'RagParser', category: 'ai-systems', tier: 'supporting', status: 'unknown', featured: false, order: 7, bodyFileId: 'projects/ai-systems/ragparser', summary: 'Local-first document normalization for RAG.', github: 'https://github.com/nirupamc/doc-for-rag' },
  { id: 'absurd-rag', title: 'Absurd RAG', category: 'ai-systems', tier: 'supporting', status: 'unknown', featured: false, order: 8, bodyFileId: 'projects/ai-systems/absurd-rag', summary: 'Earlier local RAG experimentation.', github: 'https://github.com/nirupamc/Absued-Rag' },
  { id: 'auto-apply', title: 'Kairos', category: 'products', tier: 'featured', status: 'active', featured: true, order: 9, bodyFileId: 'projects/products/auto-apply', summary: 'Human-in-the-loop recruitment workflow platform for discovery, tailoring, browser automation, and application tracking.', stack: ['React', 'TypeScript', 'Vite', 'FastAPI', 'JWT + bcrypt', 'JobSpy', 'Playwright/Patchright'], live: 'https://saaskairos.vercel.app/', liveLabel: 'Website' },
  { id: 'nerv-orbital', title: 'NERV-Orbital', category: 'full-stack', tier: 'supporting', status: 'complete', featured: false, order: 10, bodyFileId: 'projects/full-stack/nerv-orbital', stack: ['Three.js', 'React', 'TypeScript', 'Vite', 'SGP4', 'CelesTrak API'], github: 'https://github.com/nirupamc/evangalion-typeish' },
  { id: 'thrift-bazaar', title: 'ThriftBazaar', category: 'full-stack', tier: 'supporting', status: 'complete', featured: false, order: 11, bodyFileId: 'projects/full-stack/thrift-bazaar', stack: ['TypeScript', 'Node.js'], github: 'https://github.com/nirupamc/Thrift-store', live: 'https://thrift-store-ncng.vercel.app' },
  { id: 'pwa-attendance', title: 'PWA Attendance', category: 'full-stack', tier: 'supporting', status: 'complete', featured: false, order: 12, bodyFileId: 'projects/full-stack/pwa-attendance', stack: ['PWA', 'Service Workers', 'QR', 'Geolocation', 'React'], github: 'https://github.com/nirupamc/pwa-attendance' },
  { id: 'i-want-to-be-a-dj', title: 'I Want to Be a DJ', category: 'creative-tech', tier: 'featured', status: 'unknown', featured: true, order: 14, bodyFileId: 'creative/technology/i-want-to-be-a-dj', summary: 'A browser-based creative technology experiment around a 3D DJ controller.', stack: ['React', 'Three.js', 'Browser interaction'], github: 'https://github.com/nirupamc/i_want_to_be_a_dj', live: 'https://i-want-to-be-a-dj.vercel.app/', liveLabel: 'Live Demo' },
  { id: 'gamusa', title: 'Gamusa', category: 'creative', tier: 'supporting', status: 'complete', featured: false, order: 15, bodyFileId: 'creative/print-and-design/gamusa', mediaSlug: 'gamusa' },
  { id: 'kyd', title: 'KYD', category: 'creative', tier: 'supporting', status: 'active', featured: false, order: 16, bodyFileId: 'creative/print-and-design/kyd', mediaSlug: 'kyd' },
  { id: 'screen-printing', title: 'Screen Printing', category: 'creative', tier: 'supporting', status: 'unknown', featured: false, order: 17, bodyFileId: 'creative/print-and-design/screen-printing' },
]

export const projectById = new Map(projects.map((project) => [project.id, project]))
